onlyBuiltDependencies:
    - esbuild
    - sharp

overrides:
    ajv@>=7.0.0-alpha.0 <8.18.0: ">=8.18.0"
    fast-xml-parser@>=4.1.3 <5.3.6: ">=5.3.6"
    lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
    tailwindcss-animate>tailwindcss: "$tailwindcss"
