name: Push to live
on:
  push:
    tags:
      - v1.*.*

jobs:
  merge-live:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: main
      - name: Set Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Merge main branch into live
        run: |
          git fetch --unshallow
          git checkout live
          git pull
          git merge main --ff
          git push
